inherit_from: .rubocop_todo.yml

require:
    - rubocop-rails

AllCops:
    TargetRubyVersion: 2.6.4
    # 除外
    Exclude:
        - 'config.ru'
        - 'bin/**'
        - 'lib/**'
        - 'db/**/*'
        - 'config/**/*'
        - 'script/**/*'
        - 'webpacker/**/*'
        - 'node_modules/**/*'
        - 'spec/**/*'
        - 'jobs/**/*'
        - 'test/**/*'
        - !ruby/regexp /old_and_unused\.rb$/

# ヘッダコメントなしを許可
Documentation:
    Enabled: false

# Module/Classのネストのシンプル表現を許可
Style/ClassAndModuleChildren:
    Enabled: false

# 日本語コメントを許可
Style/AsciiComments:
    Enabled: false

# 文字列のFleeze設定なしを許可
Style/FrozenStringLiteralComment:
    Enabled: false

Layout/SpaceAroundMethodCallOperator:
    Enabled: true

Lint/RaiseException:
    Enabled: true

Lint/StructNewOverride:
    Enabled: true

Style/ExponentialNotation:
    Enabled: true

Style/HashEachMethods:
    Enabled: true

Style/HashTransformKeys:
    Enabled: true

Style/HashTransformValues:
    Enabled: true

Metrics/AbcSize:
    Max: 40

Metrics/MethodLength:
    Max: 15

Metrics/CyclomaticComplexity:
    Max: 10

Rails/HelperInstanceVariable:
    Enabled: false

Layout/LineLength:
    Max: 120

# TODO: エラーが発生するため暫定対応
Rails/UniqueValidationWithoutIndex:
    Enabled: false