inherit_from: .rubocop_todo.yml

require:
    - rubocop-rails

AllCops:
    TargetRubyVersion: 2.5.1
    # 除外
    Exclude:
        - 'config.ru'
        - 'bin/**'
        - 'lib/**'
        - 'db/**/*'
        - 'config/**/*'
        - 'script/**/*'
        - 'webpacker/**/*'
        - 'node_modules/**/*'
        - 'spec/**/*'
        - 'jobs/**/*'
        - 'test/**/*'
        - !ruby/regexp /old_and_unused\.rb$/

AsciiComments:
    Enabled: false

Documentation:
    Enabled: false

ClassAndModuleChildren:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Metrics/AbcSize:
    Max: 40

Rails/HelperInstanceVariable:
    Enabled: false

Layout/LineLength:
    Max: 90