version: '3'
services:
  db:
    image: postgres:11.5
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "bundle exec unicorn -c config/unicorn.rb -p 3000"
    # command: bash -c "bundle exec unicorn -c config/unicorn.rb -p 3000 -E production"
    volumes:
      - .:/ganva-app
      - public-data:/ganva-app/public
      - var-data:/ganva-app/var
    ports:
      - "3000:3000"
    depends_on:
      - db
  server:
    build:
      context: containers/nginx
    volumes:
      - ./nginx/log:/var/log/nginx
      - public-data:/ganva-app/public
      - var-data:/ganva-app/var
    depends_on:
      - web
    ports:
      - 80:80
volumes:
  public-data:
  var-data:
  postgresql-data:
    driver: local
