default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: ''

development:
  <<: *default
  database: ganva_development

test:
  <<: *default
  database: ganva_test

production:
  <<: *default
  database: ganva_production
  username: postgres
  password: <%= ENV['GANVA_DATABASE_PASSWORD'] %>
