default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: ''

development:
  <<: *default
  database: ganva_development

test:
  <<: *default
  database: ganva_test
  url: <%= ENV['DATABASE_URL'].gsub('?', '_test?' ) %>

<% if ENV['RAILS_ENV'] == 'production' %>
production:
  <<: *default
  host: <%= Rails.application.credentials.rds[:host] %>
  database: <%= Rails.application.credentials.rds[:database] %>
  username: <%= Rails.application.credentials.rds[:username] %>
  password: <%= Rails.application.credentials.rds[:password] %>
<% end %>