name: Rspec

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Prepare bundler
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Test with Rubocop
        run: |
          bundle exec rubocop
      - name: Test with Rspec
        run: |
          bundle exec rspec